/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.autowashmanager.telas;

import br.com.autowashmanager.dal.ModuloConexao;
import br.com.autowashmanager.util.DbUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author h24he
 */
public class TelaCadastroVeiculo extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroVeiculo.class.getName());

    /**
     * Creates new form TelaCadastroVeiculo
     */
    public TelaCadastroVeiculo() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    // método para pesquisar veiculo pela placa, marca, modelo e cor com filtro
    private void pesquisar_veiculo() {

        String coluna = "";

        if (rbtPlacaPesquisar.isSelected()) {
            coluna = "v.plate";
        } else if (rbtMarcaPesquisar.isSelected()) {
            coluna = "v.brand";
        } else if (rbtModeloPesquisar.isSelected()) {
            coluna = "v.model";
        } else if (rbtCorPesquisar.isSelected()) {
            coluna = "v.color";
        } else if (rbtNomeClientePesquisar.isSelected()) {
            coluna = "c.name";
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um filtro!");
            return;
        }

        try {
            String texto = txtVeiculoPesquisar.getText().trim();

            String sql;

            sql = "select v.id as id, plate as placa, brand as marca, model as modelo, color as cor, customer_id as idCliente, c.name as nomeCliente from vehicle v inner join customer c on v.customer_id = c.id where " + coluna + " like ?";

            pst = conexao.prepareStatement(sql);
            pst.setString(1, "%" + texto + "%");

            rs = pst.executeQuery();

            // a linha abaixo usa a classe DbUtils para preencher a tabela
            tblVeiculos.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // método para pesquisar cliente pelo id, nome ou telefone com filtro
    private void pesquisar_cliente() {

        String coluna = "";

        if (rbtIdPesquisar.isSelected()) {
            coluna = "id";
        } else if (rbtNomePesquisar.isSelected()) {
            coluna = "name";
        } else if (rbtTelefonePesquisar.isSelected()) {
            coluna = "phone";
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um filtro!");
            return;
        }

        try {
            String texto = txtClientePesquisar.getText().trim();

            String sql;

            if (coluna.equals("id")) {
                sql = "select id as id, name as nome, phone as telefone, email as email from customer where id = ?";

                pst = conexao.prepareStatement(sql);
                try {
                    pst.setInt(1, Integer.parseInt(texto));
                } catch (NumberFormatException e) {
                    return;
                }

            } else {
                sql = "select id as id, name as nome, phone as telefone, email as email from customer where " + coluna + " like ?";

                pst = conexao.prepareStatement(sql);
                pst.setString(1, "%" + texto + "%");
            }

            rs = pst.executeQuery();

            // a linha abaixo usa a classe DbUtils para preencher a tabela
            tblClientes.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtFiltroPesquisarVeiculo = new javax.swing.ButtonGroup();
        rbtFiltroPesquisarCliente = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeiculos = new javax.swing.JTable();
        txtVeiculoPesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rbtPlacaPesquisar = new javax.swing.JRadioButton();
        rbtMarcaPesquisar = new javax.swing.JRadioButton();
        rbtModeloPesquisar = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtCorPesquisar = new javax.swing.JRadioButton();
        rbtNomeClientePesquisar = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rbtIdPesquisar = new javax.swing.JRadioButton();
        rbtTelefonePesquisar = new javax.swing.JRadioButton();
        rbtNomePesquisar = new javax.swing.JRadioButton();
        txtClientePesquisar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("AutoWash Manager - Cadastro de Veículo");
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("* Campos Obrigatórios");

        tblVeiculos = new javax.swing.JTable() {
            public boolean isCellEditable(int rolIndex, int colIndex) {
                return false;
            }
        };
        tblVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Placa", "Marca", "Modelo", "Cor", "Id do Cliente", "Nome do Cliente"
            }
        ));
        tblVeiculos.setFocusable(false);
        tblVeiculos.getTableHeader().setReorderingAllowed(false);
        tblVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVeiculos);

        txtVeiculoPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtVeiculoPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtVeiculoPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVeiculoPesquisarKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/loupe.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        rbtFiltroPesquisarVeiculo.add(rbtPlacaPesquisar);
        rbtPlacaPesquisar.setText("placa");
        rbtPlacaPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rbtFiltroPesquisarVeiculo.add(rbtMarcaPesquisar);
        rbtMarcaPesquisar.setText("marca");
        rbtMarcaPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rbtFiltroPesquisarVeiculo.add(rbtModeloPesquisar);
        rbtModeloPesquisar.setSelected(true);
        rbtModeloPesquisar.setText("modelo");
        rbtModeloPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Pesquisar pelo:");

        rbtFiltroPesquisarVeiculo.add(rbtCorPesquisar);
        rbtCorPesquisar.setText("cor");
        rbtCorPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rbtFiltroPesquisarVeiculo.add(rbtNomeClientePesquisar);
        rbtNomeClientePesquisar.setText("nome do cliente");
        rbtNomeClientePesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel4.setText("Pesquisar pelo:");

        rbtFiltroPesquisarCliente.add(rbtIdPesquisar);
        rbtIdPesquisar.setText("id");
        rbtIdPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rbtFiltroPesquisarCliente.add(rbtTelefonePesquisar);
        rbtTelefonePesquisar.setText("telefone");
        rbtTelefonePesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rbtFiltroPesquisarCliente.add(rbtNomePesquisar);
        rbtNomePesquisar.setSelected(true);
        rbtNomePesquisar.setText("nome");
        rbtNomePesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtClientePesquisar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtClientePesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtClientePesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClientePesquisarKeyReleased(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/loupe.png"))); // NOI18N

        tblClientes = new javax.swing.JTable() {
            public boolean isCellEditable(int rolIndex, int colIndex) {
                return false;
            }
        };
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "nome", "telefone"
            }
        ));
        tblClientes.setFocusable(false);
        tblClientes.getTableHeader().setReorderingAllowed(false);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(rbtIdPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtNomePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtTelefonePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtClientePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtIdPesquisar)
                    .addComponent(rbtNomePesquisar)
                    .addComponent(rbtTelefonePesquisar)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClientePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtVeiculoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(rbtPlacaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtMarcaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtModeloPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtCorPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtNomeClientePesquisar)))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtPlacaPesquisar)
                    .addComponent(rbtMarcaPesquisar)
                    .addComponent(rbtModeloPesquisar)
                    .addComponent(jLabel3)
                    .addComponent(rbtCorPesquisar)
                    .addComponent(rbtNomeClientePesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVeiculoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVeiculosMouseClicked
        // Chamando o método de setar campos

//        setar_campos();
    }//GEN-LAST:event_tblVeiculosMouseClicked

    private void txtVeiculoPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVeiculoPesquisarKeyReleased
        // Chamando o método de pesquisar veiculo

        pesquisar_veiculo();
    }//GEN-LAST:event_txtVeiculoPesquisarKeyReleased

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // Chamando o método de setar campos

//        setar_campo_id();
    }//GEN-LAST:event_tblClientesMouseClicked

    private void txtClientePesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientePesquisarKeyReleased
        // Chamando o método de pesquisar clientes

        pesquisar_cliente();
    }//GEN-LAST:event_txtClientePesquisarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroVeiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtCorPesquisar;
    private javax.swing.ButtonGroup rbtFiltroPesquisarCliente;
    private javax.swing.ButtonGroup rbtFiltroPesquisarVeiculo;
    private javax.swing.JRadioButton rbtIdPesquisar;
    private javax.swing.JRadioButton rbtMarcaPesquisar;
    private javax.swing.JRadioButton rbtModeloPesquisar;
    private javax.swing.JRadioButton rbtNomeClientePesquisar;
    private javax.swing.JRadioButton rbtNomePesquisar;
    private javax.swing.JRadioButton rbtPlacaPesquisar;
    private javax.swing.JRadioButton rbtTelefonePesquisar;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblVeiculos;
    private javax.swing.JTextField txtClientePesquisar;
    private javax.swing.JTextField txtVeiculoPesquisar;
    // End of variables declaration//GEN-END:variables

}
