/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.autowashmanager.telas;

import javax.swing.JFrame;

/**
 *
 * @author h24he
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        confirmarSaida();
    }

    private void confirmarSaida() {
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {

                Object[] opcoes = {"Sim", "Não"};

                int resposta = javax.swing.JOptionPane.showOptionDialog(
                        null,
                        "Deseja realmente sair do sistema?",
                        "Confirmação de saída",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.QUESTION_MESSAGE,
                        null,
                        opcoes,
                        opcoes[1] // botão padrão (Não)
                );

                if (resposta == 0) {
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Menu = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenuCadastroFuncionario = new javax.swing.JMenuItem();
        MenuCadastroCliente = new javax.swing.JMenuItem();
        MenuCadastroVeiculo = new javax.swing.JMenuItem();
        MenuEmissao = new javax.swing.JMenu();
        MenuEmissaoOS = new javax.swing.JMenuItem();
        MenuGestao = new javax.swing.JMenu();
        MenuGestaoProdutos = new javax.swing.JMenuItem();
        MenuGestaoContas = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("AutoWash Manager - Menu");

        MenuCadastro.setText("Cadastro");
        MenuCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuCadastroFuncionario.setText("Funcionário");
        MenuCadastroFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCadastroFuncionario.addActionListener(this::MenuCadastroFuncionarioActionPerformed);
        MenuCadastro.add(MenuCadastroFuncionario);

        MenuCadastroCliente.setText("Cliente");
        MenuCadastroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCadastroCliente.addActionListener(this::MenuCadastroClienteActionPerformed);
        MenuCadastro.add(MenuCadastroCliente);

        MenuCadastroVeiculo.setText("Veículo");
        MenuCadastroVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuCadastroVeiculo.addActionListener(this::MenuCadastroVeiculoActionPerformed);
        MenuCadastro.add(MenuCadastroVeiculo);

        Menu.add(MenuCadastro);

        MenuEmissao.setText("Emissão");
        MenuEmissao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuEmissaoOS.setText("Ordem de Serviço");
        MenuEmissaoOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuEmissaoOS.addActionListener(this::MenuEmissaoOSActionPerformed);
        MenuEmissao.add(MenuEmissaoOS);

        Menu.add(MenuEmissao);

        MenuGestao.setText("Gestão");
        MenuGestao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        MenuGestaoProdutos.setText("Produtos");
        MenuGestaoProdutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuGestaoProdutos.addActionListener(this::MenuGestaoProdutosActionPerformed);
        MenuGestao.add(MenuGestaoProdutos);

        MenuGestaoContas.setText("Contas");
        MenuGestaoContas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuGestaoContas.addActionListener(this::MenuGestaoContasActionPerformed);
        MenuGestao.add(MenuGestaoContas);

        Menu.add(MenuGestao);

        MenuRelatorios.setText("Relatórios");
        MenuRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.add(MenuRelatorios);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroFuncionarioActionPerformed
        // Chamando a Tela de Cadastro de Funcionário
        
        TelaCadastroFuncionario telaFuncionario = new TelaCadastroFuncionario();
        telaFuncionario.setVisible(true);
    }//GEN-LAST:event_MenuCadastroFuncionarioActionPerformed

    private void MenuCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroClienteActionPerformed
        // Chamando a Tela de Cadastro de Cliente
        
        TelaCadastroCliente telaCliente = new TelaCadastroCliente();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_MenuCadastroClienteActionPerformed

    private void MenuCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastroVeiculoActionPerformed
        // Chamando a Tela de Cadastro de Veículo
        
        TelaCadastroVeiculo telaVeiculo = new TelaCadastroVeiculo();
        telaVeiculo.setVisible(true);
    }//GEN-LAST:event_MenuCadastroVeiculoActionPerformed

    private void MenuEmissaoOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEmissaoOSActionPerformed
        // Chamando a Tela de Emissão de Ordem de Serviço
        
        TelaEmissaoOS telaOS = new TelaEmissaoOS();
        telaOS.setVisible(true);
    }//GEN-LAST:event_MenuEmissaoOSActionPerformed

    private void MenuGestaoProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGestaoProdutosActionPerformed
        // Chamando a Tela de Gestão de Produtos
        
        TelaGestaoProdutos gestaoProdutos = new TelaGestaoProdutos();
        gestaoProdutos.setVisible(true);
    }//GEN-LAST:event_MenuGestaoProdutosActionPerformed

    private void MenuGestaoContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGestaoContasActionPerformed
        // Chamando a Tela de Gestão de Contas
        
        TelaGestaoContas gestaoContas = new TelaGestaoContas();
        gestaoContas.setVisible(true);
    }//GEN-LAST:event_MenuGestaoContasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenuItem MenuCadastroCliente;
    private javax.swing.JMenuItem MenuCadastroFuncionario;
    private javax.swing.JMenuItem MenuCadastroVeiculo;
    private javax.swing.JMenu MenuEmissao;
    private javax.swing.JMenuItem MenuEmissaoOS;
    private javax.swing.JMenu MenuGestao;
    private javax.swing.JMenuItem MenuGestaoContas;
    private javax.swing.JMenuItem MenuGestaoProdutos;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
